name: PULL REQUEST JOB
run-name: BUILDING BRANCH ${{ github.ref }}

on:
  pull_request:
    types:
      - edited
  workflow_dispatch:
    inputs:
      bucket:
        description: 'Bucket where to deploy'
        default: profiles-data
        type: string
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SET UP PYTHON 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: INSTALL DEPENDENCIES
        run: |
          if [ -f application/requirements.txt ]; then pip install -r application/requirements.txt; fi
          pip install -e .
      - name: CHECK SYNTAX
        run: |
          # stop the build if there are Python syntax errors
          black --check .
      - name: TEST
        run: |
          pytest application/test
          

  release:
    runs-on: ubuntu-latest
    needs: [build]
    environment: student_env
    steps:
      - uses: actions/checkout@v3
      - name: PACKAGE
        run: |
          zip -r code.zip application/src
      - name: PUSH TO S3
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_REGION=${{ vars.AWS_REGION }} 
          export AWS_ROLE_ARN=${{ vars.ROLE_ARN }}
          aws s3 cp code.zip  s3://profiles-data/code.zip

